# Site settings
title: Josie Zhang
email: josiezhang84@gmail.com
url: https://github.com/jiayuezhang84
description: "Jiayue (Josie) Zhang is a passionate software engineer with a relentless curiosity for all things tech. from tax accounting to computer science, I will never change my mind to be a specialist in any field. I've spent years in the digital trenches, sculpting lines of code into powerful solutions that make life simpler and more efficient. "
keywords: "software engineer, tax accountant, specialty, python, tech, private equity, hedge fund, northeastern, Boston, New York, consulting, PM"
skills: "Software Engineer - CPA - Photographer"
meta_author: Jiayue Zhang

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: jzhang

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 233140 #A2122F
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Social
  credits: Contact me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/josie-zhang  
  - title: instagram
    url: https://www.instagram.com/josie_jyz/
  - title: github
    url: https://github.com/jiayuezhang84
    
# Postal address (add as many lines as necessary)
address:
  - line: The Athens of America
  - line: Boston, MA 02114

# Credits content
credits: reach out to me anytime by filling out the "CONTACT ME" Form above.

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
